### ISSUE TITLE
Week 9 Functions Lab Ready

### ISSUE THREAD

**Issue by kganser-matc** [madisoncollege-it-programs/python-scripting-kganser-matc#11]

**Comment by cethenmc** [comment]
Great work!  8 of 8

**Comment by cethenmc** [comment]
Kaden - I will also add that the tempconversion.py was intended to be run through the "main()" function, which is why the part title looks like this:  "Script 2 - Temp Conversion (**Main**)."  It was not super clear, so I am not deducting points.  However, you may want to consider modifying your tempconversion.py script to run that way.
