### ISSUE TITLE
Midterm-Jpark is ready

### ISSUE THREAD

**Issue by kganser-matc** [madisoncollege-it-programs/python-scripting-kganser-matc#8]

**Comment by cethenmc** [comment]
Thanks for putting in a very solid effort on this part of the midterm.  The first part I analyze is program execution.  I figured out in a couple of seconds that I could log in using please as my username and please as my password.  I can do the same with username dnedry and password dnedry.  Of course, I could also log in as please for the username and dnedry as the password.  This problem is with line 16 in the code (1 pt).  Lines 21 - 26 should be consolidated into one if statement and use the input command without hardcoding values (2 pts).  Score 30/33.
